### PR TITLE
Remove stashed nodes from accessibility tree.

### LINKED ISSUE #1119: Panic with stashed textarea:
We're doing a `CollapsePanel` where we have a button in a header that collapses (hides) a child, like for use within an accordion panel.

This sets the child widget to be stashed in the layout function, but then we get this assert during startup:

```
thread 'main' panicked at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry/src/widgets/text_area.rs:941:14:
We just performed a layout
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_display
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:269:5
   3: core::option::expect_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/option.rs:2049:5
   4: core::option::Option<T>::expect
             at /Users/bruce/.rustup/toolchains/1.88-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:958:21
   5: <masonry::widgets::text_area::TextArea<_> as masonry_core::core::widget::Widget>::accessibility
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry/src/widgets/text_area.rs:941:14
   6: masonry_core::passes::accessibility::build_accessibility_tree
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:62:9
   7: masonry_core::passes::accessibility::build_accessibility_tree::{{closure}}
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:84:13
   8: masonry_core::passes::recurse_on_children
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/mod.rs:105:9
   9: masonry_core::passes::accessibility::build_accessibility_tree
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:76:5
  10: masonry_core::passes::accessibility::build_accessibility_tree::{{closure}}
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:84:13
  11: masonry_core::passes::recurse_on_children
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/mod.rs:105:9
  12: masonry_core::passes::accessibility::build_accessibility_tree
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:76:5
  13: masonry_core::passes::accessibility::build_accessibility_tree::{{closure}}
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:84:13
  14: masonry_core::passes::recurse_on_children
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/mod.rs:105:9
  15: masonry_core::passes::accessibility::build_accessibility_tree
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:76:5
  16: masonry_core::passes::accessibility::build_accessibility_tree::{{closure}}
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:84:13
  17: masonry_core::passes::recurse_on_children
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/mod.rs:105:9
  18: masonry_core::passes::accessibility::build_accessibility_tree
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:76:5
  19: masonry_core::passes::accessibility::run_accessibility_pass
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/passes/accessibility.rs:192:5
  20: masonry_core::app::render_root::RenderRoot::redraw
             at /Users/bruce/.cargo/git/checkouts/xilem-420a6f61d3d10f60/906244d/masonry_core/src/app/render_root.rs:444:27
  21: nx_masonry_winit::event_loop_runner::MasonryState::handle_signals
             at ./crates/nx-masonry-winit/src/event_loop_runner.rs:844:40
```

### PR DESCRIPTION
**Pull request by PoignardAzur**
Fixes #1119.

### CODE REVIEW

File: masonry_core/src/passes/accessibility.rs [hunk 1]
```diff
@@ -120,9 +129,6 @@ fn build_access_node(
     if ctx.is_disabled() {
         node.set_disabled();
     }
-    if ctx.is_stashed() {
```
Comment (waywardmonkeys) [inline masonry_core/src/passes/accessibility.rs:123]: Is it worthwhile to potentially have a debug assert here that isn't stashed just to verify that in debug builds?

**Review by waywardmonkeys — APPROVED** [review]

File: masonry_core/src/passes/accessibility.rs (hunk 1 above)
Comment (PoignardAzur) [reply masonry_core/src/passes/accessibility.rs:123]: Wouldn't hurt, I suppose.
