### PR TITLE
Optimize and fix window resizing.

### LINKED ISSUE #979: When the minimize button was clicked, the program crashed.
```
PS D:\Workspace\VSCode_Workspace\learn_gui\learn_xilem> cargo r
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.50s
     Running `target\debug\learn_xilem.exe`
---
Writing full logs to C:\Users\paul\AppData\Local\Temp\masonry-0001747562638618-dense.log
---
10:03:58.980Z DEBUG accessibility: Running ACCESSIBILITY pass with rebuild_all
Initialising in parallel using 6 threads
10:03:59.177Z DEBUG dispatch_text_event: Running ON_TEXT_EVENT pass with WindowFocusChange
10:03:59.177Z DEBUG dispatch_text_event: ON_TEXT_EVENT finished handled=false
10:04:01.216Z DEBUG dispatch_pointer_event: Running ON_POINTER_EVENT pass with Cancel
10:04:01.217Z DEBUG dispatch_pointer_event: ON_POINTER_EVENT finished handled=false
10:04:01.217Z DEBUG dispatch_text_event: Running ON_TEXT_EVENT pass with WindowFocusChange
10:04:01.219Z DEBUG dispatch_text_event: ON_TEXT_EVENT finished handled=false

thread 'main' panicked at C:\Users\paul\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-24.0.3\src\backend\wgpu_core.rs:1423:26:
wgpu error: Validation Error

Caused by:
  In Device::create_texture
    Dimension X is zero


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\learn_xilem.exe` (exit code: 101)
```

### PR DESCRIPTION
**Pull request by xStrom**
The Masonry `Window` struct was being created with a `0x0` size and a `1.0` scale factor. Initial layout and render passes ran with that. Then there would be an event for scale change (but still zero size) and another pass. Then there would be a size change event and useful work would finally take place.

This PR removes all that early useless work and creates the `Window` struct immediately with the correct info.

---

A bunch of places would ask Winit for the window size, including the `render` function. At least on Windows this would cause Winit to execute a syscall. That is needless overhead, especially in a hot path, because we already store that info in the `RenderRoot` struct.

This PR exposes that size info.

---

Masonry has been suffering from crashes on Windows 11 whenever a window would be minimized or otherwise resized to zero (#979).

This PR resolves that issue. Fixes #979.

First, I refactored the redraw code so that there is a single source of truth for the behavior. There was already divergence with the first frame not doing the `AnimFrame` event and more issues could easily follow with such a duplicated approach.

The redraw refactoring also introduced on-demand surface creation. This is useful to actually solve the Windows crash issue, as now we can just delete the old surface when a zero sized resize event comes in. Whenever a reasonable size redraw happens, the surface will be recreated.

---

I have tested this as working nicely on Windows 11. Trying out crazy resizings (especially to zero!), minimizing, and suspending on other platforms would be very welcome.

### CODE REVIEW

**Review by jaredoconnell — COMMENTED** [review]
This looks like a good improvement. I tested it on Mac OS and didn't notice any issues. I'll test it on Windows later.

File: masonry_testing/src/harness.rs [hunk 1]
```diff
@@ -349,7 +350,6 @@ impl<W: Widget> TestHarness<W> {
         };
 
         // Set up the initial state, and clear invalidation flags.
-        harness.process_window_event(WindowEvent::Resize(window_size));
```
Comment (DJMcNab) [inline masonry_testing/src/harness.rs:352]: As far as I understand, the initial size being zero was an intentional decision, as a sort of passive version of #788. For tests specifically, I think that defaulting to that behaviour is possibly actually a good thing.

File: masonry_winit/src/event_loop_runner.rs [hunk 2]
```diff
@@ -458,6 +457,58 @@ impl MasonryState<'_> {
...
+        // TODO: this calculation uses wall-clock time of the paint call, which
+        // potentially has jitter.
+        //
+        // See https://github.com/linebender/druid/issues/85 for discussion.
+        let last = self.last_anim.take();
+        let elapsed = last.map(|t| now.duration_since(t)).unwrap_or_default();
+
+        window
+            .render_root
+            .handle_window_event(WindowEvent::AnimFrame(elapsed));
```
Comment (DJMcNab) [inline masonry_winit/src/event_loop_runner.rs:496]: Fwiw, we probably need to handle signals after an animation (see e.g. #985). That being said, everything about animations will need to change in the future anyway, and this isn't a regression here.

**Review by DJMcNab — APPROVED** [review]
I'm not sure about the change in the test harness, because an initial layout/render at zero size does have value, in helping to encourage greater robustness.

Otherwise, this PR looks good and works well. For some reason it is forbidden in the Wayland protocol to have a zero sized *window* (even if there will be compositor provided decorations), so I haven't been able to test it on this machine (something in the stack sets a default minimum size, and trying to work past it gives a gnarly error).
But it hasn't regressed anything, and 
I've also tested on Android (which ran into #1377), and the interaction with suspension/resumption seems to be stable.

File: masonry_winit/src/event_loop_runner.rs (hunk 2 above)
Comment (xStrom) [reply masonry_winit/src/event_loop_runner.rs:496]: Makes sense, but yeah it wasn't done before either, so that'll be future work.

File: masonry_testing/src/harness.rs (hunk 1 above)
Comment (xStrom) [reply masonry_testing/src/harness.rs:352]: The initial window size in testing is controlled by `TestHarnessParams::window_size`, so if starting with zero is useful, those specific tests can set it accordingly. Indeed, that is exactly what the zero size tests added in #1232 do.

The removal of this specific event is because it's no longer needed and no longer matches actual app behavior. It would also always send the same value that the window was initialized with. (*There's probably value in emulating the behavior of the startup Winit resize event, but that would be a bit later, not at this moment in the lifecycle.*)

**Comment by xStrom** [comment]
I'm especially happy to hear that Android suspend still works!

I'll go ahead and merge this. If anyone finds issues, we'll deal with those as follow-up work.

File: masonry_testing/src/harness.rs (hunk 1 above)
Comment (DJMcNab) [reply masonry_testing/src/harness.rs:352]: The point is that this change reduces coverage of zero size handling for a large number of widgets.

Now maybe that's fine, and we probably should have such tests explicitly instead. But it is a regression in what's covered.

Either way, this isn't worth worrying about too much, but it probably is worth opening an issue for "explicit zero size testing of widgets individually"
