### PR TITLE
xilem_web: Fix mathml example (use `style` method instead of untyped `attr`)

### LINKED ISSUE #295: [`xilem_web`] Panic in `mathml_svg` example: "styles should be set using the `style` method"
This only happens when running with the `debug` profile. `--release` works fine.

Looks like an internal debug assertion is failing:

```
ERROR app: panicked at crates/xilem_web/src/context.rs:338:9:
styles should be set using the `style` method

Stack:

__wbg_get_imports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://127.0.0.1:1334/api/wasm.js:259:13
__wbg_new_abda76e883ba8a5f externref shim@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1903]:0x6754c
console_error_panic_hook::Error::new::hb71ebe39408f4bc5@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1347]:0x606c1
console_error_panic_hook::hook_impl::h50653ea3a54bf5ba@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[292]:0x34bc9
console_error_panic_hook::hook::hf335411fa0078473@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1660]:0x651fb
core::ops::function::Fn::call::h216cccddca40524d@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1440]:0x62098
std::panicking::rust_panic_with_hook::h5ca5fd3b2064be1b@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[570]:0x492c3
std::panicking::begin_panic_handler::{{closure}}::h04d653c63f99fdc6@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[705]:0x4f80e
std::sys_common::backtrace::__rust_end_short_backtrace::h99eba4e509e8f1e3@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1959]:0x678d1
rust_begin_unwind@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1497]:0x62ecd
core::panicking::panic_fmt::h2582bddf31c1c986@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1601]:0x645f6
xilem_web::context::Cx::add_attr_to_element::h15f64463f7beb623@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[178]:0x27425
<xilem_web::attribute::Attr<E,T,A> as xilem_web::view::View<T,A>>::build::hb6e176c94e4cbcce@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1069]:0x5a831
<V as xilem_web::view::ViewSequence<T,A>>::build::{{closure}}::h8badfa3b780c8b65@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1388]:0x6127b
xilem_web::context::Cx::with_new_pod::h8d7e0e28aa00a522@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[130]:0x1e68f
<V as xilem_web::view::ViewSequence<T,A>>::build::h1c1b5f85a7571e1f@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[129]:0x1e34e
<(V0,V1,V2,V3) as xilem_web::view::ViewSequence<T,A>>::build::h623758f25864d380@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[141]:0x20b81
<xilem_web::elements::svg::Svg<T,A,VS> as xilem_web::view::View<T,A>>::build::{{closure}}::h6f7112d198d672fc@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1151]:0x5c75d
xilem_web::context::Cx::with_new_id::h5b5ff16b9036d591@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[766]:0x51e1a
<xilem_web::elements::svg::Svg<T,A,VS> as xilem_web::view::View<T,A>>::build::h5df0c79b00a1e388@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[70]:0xbb6d
<xilem_web::attribute::Attr<E,T,A> as xilem_web::view::View<T,A>>::build::h714899faa4b9e17b@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1067]:0x5a77d
<xilem_web::attribute::Attr<E,T,A> as xilem_web::view::View<T,A>>::build::hc7d6e82f8234feef@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1071]:0x5a8f8
<V as xilem_web::view::ViewSequence<T,A>>::build::{{closure}}::hf398834fd2b6ee43@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1390]:0x61307
xilem_web::context::Cx::with_new_pod::h6b2aa889ab8b4a79@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[523]:0x46717
<V as xilem_web::view::ViewSequence<T,A>>::build::h3ba027c63bd23ea5@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[509]:0x4592a
<(V0,V1,V2,V3) as xilem_web::view::ViewSequence<T,A>>::build::h9065dea392a5901a@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[154]:0x23184
<xilem_web::elements::html::Div<T,A,VS> as xilem_web::view::View<T,A>>::build::{{closure}}::hbfedec678951ab55@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1147]:0x5c5e2
xilem_web::context::Cx::with_new_id::h1d62b4ce701ac429@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[689]:0x4ed24
<xilem_web::elements::html::Div<T,A,VS> as xilem_web::view::View<T,A>>::build::hea2276e6c43b5ef1@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[66]:0x9fd1
xilem_web::app::AppInner<T,V,F>::ensure_app::h6141b71038f9e967@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[143]:0x211f4
xilem_web::app::App<T,V,F>::run::h67076ef4c692a50d@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[497]:0x44dbd
mathml_svg::main::hf575d8b890a30d5e@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[771]:0x52101
core::ops::function::FnOnce::call_once::h6e4f000d986d5ade@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1605]:0x646cb
std::sys_common::backtrace::__rust_begin_short_backtrace::hc3799b89fbdab980@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1656]:0x6512b
std::rt::lang_start::{{closure}}::h97fbb8b345749f57@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[842]:0x546fe
std::rt::lang_start_internal::h66edba0246e4a665@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[421]:0x3fa52
std::rt::lang_start::h36ed7e0a2fd82bef@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[810]:0x5360b
main@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1847]:0x66feb
@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1929]:0x6775a
@http://127.0.0.1:1334/api/wasm.wasm:wasm-function[1977]:0x67972
__wbg_finalize_init@http://127.0.0.1:1334/api/wasm.js:553:26
__wbg_init@http://127.0.0.1:1334/api/wasm.js:587:28
```

### PR DESCRIPTION
**Pull request by Philipp-M**
Fixes #295

Also implements `IntoStyles` for `[impl IntoStyles; N]`

### CODE REVIEW

File: crates/xilem_web/web_examples/mathml_svg/src/main.rs [hunk 1]
```diff
@@ -83,8 +88,7 @@ pub fn main() {
                 ml::msup((ml::mi(format!("{}", t.b)), ml::mn("2"))),
                 ml::mo("="),
                 ml::msup((ml::mi(format!("{c}")), ml::mn("2"))),
-            )))
-            .attr("style", "width: 100%"),
+            ))),
```
Comment (waywardmonkeys) [inline crates/xilem_web/web_examples/mathml_svg/src/main.rs:91]: What happened tot his one?

Comment (Philipp-M) [reply crates/xilem_web/web_examples/mathml_svg/src/main.rs:91]: Well, `style` is not supported by `web_sys` currently for MathML elements (and thus by xilem_web, as it relies on web_sys currently), I don't think this had an effect anyways.

But I looked the [relevant interface](https://developer.mozilla.org/en-US/docs/Web/API/MathMLElement) up, which indeed supports `style`, so I guess when we don't want to specially handle this (and I think it will require some very special handling and likely additional wasm bloat for something that is very seldom used), it needs to be implemented in web_sys via an additional webidl interface (shouldn't be too hard though).

**Review by waywardmonkeys — APPROVED** [review]
